title: Welcome to Team Alpha's Homepage!
description: We're Team Alpha - we strive to build products with a focus on user privacy without compromising on comfort and usability.
theme: jekyll-theme-leap-day
